"""add_users_pending_email

Revision ID: 023ff6b68541
Revises: 1f3c7d4188de
Create Date: 2026-08-27 19:38:21.682254
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '023ff6b68541'
down_revision: str | None = '1f3c7d4188de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
