"""add_onboarding_tables

Revision ID: 2778a43e066d
Revises: 023ff6b68541
Create Date: 2026-08-27 21:39:36.912050
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2778a43e066d'
down_revision: str | None = '023ff6b68541'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maladies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('localisation', sa.String(length=255), nullable=True),
    sa.Column('nom_complet', sa.String(length=255), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.String(length=32), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('notifications_accordees', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('batterie_exemptee', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patient_aidant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('aidant_id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.String(length=32), server_default='actif', nullable=False),
    sa.Column('niveau_permission', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"observance": true, "constantes": false}\'::jsonb'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aidant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_aidant_aidant_id'), 'patient_aidant', ['aidant_id'], unique=False)
    op.create_index(op.f('ix_patient_aidant_patient_id'), 'patient_aidant', ['patient_id'], unique=False)
    op.create_table('patient_traitements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('maladie_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maladie_id'], ['maladies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_traitements_maladie_id'), 'patient_traitements', ['maladie_id'], unique=False)
    op.create_index(op.f('ix_patient_traitements_patient_id'), 'patient_traitements', ['patient_id'], unique=False)
    op.create_table('sync_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_codes_code'), 'sync_codes', ['code'], unique=False)
    op.create_index(op.f('ix_sync_codes_patient_id'), 'sync_codes', ['patient_id'], unique=False)
    op.add_column('users', sa.Column('nom_complet', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('sexe', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('localisation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'localisation')
    op.drop_column('users', 'sexe')
    op.drop_column('users', 'date_naissance')
    op.drop_column('users', 'nom_complet')
    op.drop_index(op.f('ix_sync_codes_patient_id'), table_name='sync_codes')
    op.drop_index(op.f('ix_sync_codes_code'), table_name='sync_codes')
    op.drop_table('sync_codes')
    op.drop_index(op.f('ix_patient_traitements_patient_id'), table_name='patient_traitements')
    op.drop_index(op.f('ix_patient_traitements_maladie_id'), table_name='patient_traitements')
    op.drop_table('patient_traitements')
    op.drop_index(op.f('ix_patient_aidant_patient_id'), table_name='patient_aidant')
    op.drop_index(op.f('ix_patient_aidant_aidant_id'), table_name='patient_aidant')
    op.drop_table('patient_aidant')
    op.drop_table('patients')
    op.drop_table('maladies')
    # ### end Alembic commands ###
