"""add_notification_logs

Revision ID: a991474596b1
Revises: 2778a43e066d
Create Date: 2026-08-27 21:56:34.368143
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a991474596b1'
down_revision: str | None = '2778a43e066d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destinataire_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('declencheur', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('envoye_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destinataire_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_destinataire_id'), 'notification_logs', ['destinataire_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_destinataire_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
